#include "InputComponent.h"

struct InputComponent {
    std::vector<int> keys;  // List of keys to listen for
    std::function<void()> onKeyPress;  // Callback for key press
    //generated by chatgpt, just as a starting point
    //unused
};
