#include "InputSystem.h"
#include "Components\InputComponent.h"

class InputSystem {
public:
    void update() {
        // Process keyboard events and update entities accordingly
        for (auto& entity : entitiesWithInput) {
            auto& inputComp = entity.getComponent<InputComponent>();
            for (auto& key : inputComp.keys) {
                if (isKeyPressed(key)) {
                    inputComp.onKeyPress();  // Trigger the callback
                }
            }
        }
    }

private:
    std::vector<Entity> entitiesWithInput;  // Keep track of entities with input components
};

//generated by chatgpt